services:
  app:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_REMOVE_VOLUMES: true
      WATCHTOWER_LABEL_ENABLE: true
      WATCHTOWER_SCHEDULE: "[UPDATE_SCHEDULE_HERE]"
      WATCHTOWER_NOTIFICATIONS: "email"
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: "[EMAIL_FROM_HERE]"
      WATCHTOWER_NOTIFICATION_EMAIL_TO: "[EMAIL_TO_HERE]"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: "[EMAIL_SERVER_HERE]"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: "[EMAIL_SERVER_PORT_HERE]"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: "[EMAIL_SERVER_USER_HERE]"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: "[EMAIL_SERVER_PASSWORD_HERE]"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
